# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-26 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='prid_quo',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
